//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporSalonuUygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PersonelBilgileri
    {
        public int Personel_Id { get; set; }
        public string TC_No { get; set; }
        public string Ad_Soyad { get; set; }
        public string Kul_adi { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Giris_Karti { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
    }
}
