//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporSalonuUygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UyeBilgileri
    {
        public int Uye_Id { get; set; }
        public string Ad_Soyad { get; set; }
        public string TC_No { get; set; }
        public Nullable<int> Telefon { get; set; }
        public Nullable<int> Giris_Karti { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<int> Gun { get; set; }
        public Nullable<int> Boy { get; set; }
        public Nullable<int> Kilo { get; set; }
        public Nullable<int> Yas { get; set; }
        public string Kayit_Suresi { get; set; }
        public Nullable<int> Program_Sec { get; set; }
    }
}
