//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporSalonuUygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AntremanProgrami
    {
        public int Program_Id { get; set; }
        public Nullable<int> Uye_Id { get; set; }
        public Nullable<int> Antrenor_Id { get; set; }
        public Nullable<int> Baslangic_Saati { get; set; }
        public Nullable<int> Bitis_Saati { get; set; }
    }
}
