//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporSalonuUygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_antrenor
    {
        public int Antrenor_Id { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<System.DateTime> Dogum_Tarihi { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string E_Posta { get; set; }
    }
}
